[build]
builder = "NIXPACKS"

[deploy]
startCommand = "alembic upgrade head && python -u -m scripts.seed_questions && python -u -m pylevelup"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
